# Generated by Django 3.2.2 on 2021-10-27 05:26

from django.db import migrations, models
import getImage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=200)),
                ('image', models.ImageField(default='../media/james.jpg', upload_to=getImage.models.image_upload_path2)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=200)),
                ('image', models.ImageField(default='../media/james.jpg', upload_to=getImage.models.image_upload_path1)),
            ],
        ),
    ]
